---
dependency:
  name: galaxy
driver:
  name: docker
lint: |
   yamllint .
   ansible-lint .
platforms:
  - name: instance
    image: docker.io/pycontribs/ubuntu
    pre_build_image: true
    capabilities:
      - SYS_ADMIN
    volumes:
      - /sys/fs/cgroup:/sys/fs/cgroup:rw
    privileged: true
provisioner:
  name: ansible
verifier:
  name: ansible
